# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: sunxc 
subtitle: 个人博客
author: sunXiChun
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://github.com/sunXiChun
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huweihuang

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:sunXiChun/sunXiChun.github.io.git
  branch: master



# Site settings
SEOTitle: sunxc | Blog
email: 996058968@qq.com
description: ""
keyword: ""
header-img: /img/header_img/home.png
article-img: /img/header_img/archive.png
404-img: /img/header_img/404.png
signature: false #show signature
signature-img: img/signature/BeanTechSign-white.png 

github_username:    sunXiChun
facebook_username:  xichuns

# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "在道德与不道德的区分之外，有片田野。我将在那里见你。"
sidebar-avatar: /img/supreme.png       # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
#- category

# widget behavior
## Archive
archives-img: /img/header_img/archive.png
archive_type: 'monthly'
show_count: true


## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value

## Friends
friends: [
    {
		    title: "zld iOS Developer",
		    href: "https://github.com/zld"
	  },
	  {
		    title: "Petrie PHP Programmer",
		    href: "https://github.com/Petrie"
	  },
	  {
		    title: "骁驰 iOS Developer",
		    href: "https://lije024.github.io/"
	  }
]

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'

# # MeingJS support for Aplayer
# # reference: https://github.com/metowolf/MetingJS & https://github.com/MoePlayer/APlayer
# metingjs: false
# data-id: 2423410161
# data-server: netease  
# data-type: playlist
# data-fixed: true
#   # data-mini:
#   # data-autoplay:   

# leancloud_visitors:
#   enable: true
#   app_id: XP6VS7i3AEBgkUvaCmtHKMNp-gzGzoHsz
#   app_key: N0RIVDhplJ5upwPvyLGRcpDg

valine: 
  enable: true
  appid:  kpXPEmb4vatowyHxa4dYvy0N-gzGzoHsz
  appkey:  qAL8XVpfEOi1zqGiglHYPWsv
  verify: false #验证码
  notify: false #评论回复提醒
  avatar: mm #评论列表默认头像样式
  placeholder: Just go go #评论框占位符

